name: Create Nuget package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Net Core version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Generate Nuget.config
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" > NuGet.config
          echo "<configuration>" >> NuGet.config
          echo "<packageSources>" >> NuGet.config
          echo "<add key=\"nuget.org\" value=\"https://api.nuget.org/v3/index.json\" protocolVersion=\"3\" />" >> NuGet.config
          echo "<add key=\"GPR\" value=\"${{ secrets.NUGET_SOURCE_FULL }}\" />" >> NuGet.config
          echo "</packageSources>" >> NuGet.config
          echo "<packageSourceCredentials>" >> NuGet.config
          echo "<GPR>" >> NuGet.config
          echo "<add key=\"Username\" value=\"${{ secrets.NUGET_USERNAME }}\" />" >> NuGet.config
          echo "<add key=\"ClearTextPassword\" value=\"${{ secrets.NUGET_PASSWORD }}\" />" >> NuGet.config
          echo "</GPR>" >> NuGet.config
          echo "</packageSourceCredentials>" >> NuGet.config
          echo "</configuration>" >> NuGet.config

      - name: Generate package
        run: dotnet pack --configuration Release

      - name: Push package
        run: |
          for package in ./bin/Release/*.nupkg
            do
              curl -vX PUT -u "${{ secrets.NUGET_USERNAME }}:${{ secrets.NUGET_PASSWORD }}" -F package=@$package ${{ secrets.NUGET_SOURCE }}
            done
